name: 01 primer pipeline

on: workflow_dispatch

jobs:
  echo-holamundo:
    runs-on: ubuntu-latest
    steps:
      - name: Hola Mundo
        run: echo "Hola mundo!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Adiós Mundo
        run: echo "Adiós mundo!"