name: 06-contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

on:
  push:
  workflow_dispatch: 
    inputs:
      debug:
        type: boolean
        default: false

env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    steps:
      - name: Display Information
        run: |
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_ACTOR: ${{ github.actor }}"
          echo "GITHUB_WORKFLOW: ${{ github.workflow }}"
          echo "GITHUB_RUN_ID: ${{ github.run_id }}"
          echo "GITHUB_RUN_NUMBER: ${{ github.run_number }}"
      - name: Retrieve Variables
        run: |
          echo "MY_VAR: ${{ vars.MY_VAR }}"
      - name: Print Env Variables
        env:
          MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "MY_WORKFLOW_VAR: ${{ env.MY_WORKFLOW_VAR }}"
          echo "MY_OVERWRITTEN_VAR: ${{ env.MY_OVERWRITTEN_VAR }}"
      - name: Print Env Variables
        run: |
          echo "MY_WORKFLOW_VAR: ${{ env.MY_WORKFLOW_VAR }}"
          echo "MY_OVERWRITTEN_VAR: ${{ env.MY_OVERWRITTEN_VAR }}"

